name: Release Single Image
on:
  workflow_dispatch:
    inputs:
      pipeline-argument:
        description: 'Argument to pass to pipeline'
        required: true
jobs:
  release-single-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.4'
          architecture: 'x64'

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('requirements.txt') }}

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: release.daocloud.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      # template: .action_templates/steps/set-up-qemu.yaml
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Publish Image To DaoCloud
        run: python pipeline.py --image-name ${{ github.event.inputs.pipeline-argument }} --tag 0.10.0
        env:
          MONGODB_COMMUNITY_CONFIG: "${{ github.workspace }}/scripts/ci/config.json"
         
          GRS_USERNAME: "${{ vars.GRS_USERNAME }}"
          GRS_PASSWORD: "${{ secrets.GRS_PASSWORD }}"
